theme: minima
title: Can Do!
author: Nakia Russell
description: ("With little time on her hands and too many projects to do; Nakia finds herself overwhelmed and overworked. Despite the odds with family, friends, and their love and support on her side. That can do spirit! Finds the heat it needs to give, so she can finish it all.")
